// types.ts
import React from 'react';

/**
 * Represents the user's input for generating startup ideas.
 */
export interface UserInput {
  industry: string;
  targetAudience: string;
  budgetRange: string;
  timeToMarket: string;
  skills: string[];
}

/**
 * Represents a single validated startup idea generated by the AI.
 */
export interface StartupIdea {
  title: string;
  description: string;
  marketOpportunityScore: number;
  marketOpportunityExplanation: string;
  targetMarketSize: string;
  keyCompetitors: { name: string; description: string }[];
  currentTrends: { trend: string; insight: string }[]; // Modified to include insight
  estimatedStartupCosts: string;
  revenuePotential: string;
  riskAnalysis: 'Low' | 'Medium' | 'High';
  riskFactors: string[];
  nextSteps: string[];
  requiredResources: { team: string[]; tools: string[]; technology: string[] };
  timeToMarket: string;
  successStories?: { title: string; link: string }[];
  resourceLinks?: { title: string; link: string }[];
}

/**
 * The expected structure of the JSON response from the Gemini API.
 */
export interface GeminiIdeaResponse {
  ideas: StartupIdea[];
  groundingLinks?: { uri: string; title: string; }[];
}

/**
 * Represents a single search grounding chunk from the Gemini API.
 */
export interface GroundingChunk {
  web?: {
    uri: string;
    title: string;
  };
  maps?: {
    uri: string;
    title: string;
    placeAnswerSources?: {
      reviewSnippets?: {
        uri: string;
        title: string;
      }[];
    };
  };
}

/**
 * Props for a common button component.
 */
export interface ButtonProps {
  onClick: () => void;
  children: React.ReactNode;
  className?: string;
  disabled?: boolean;
  type?: 'button' | 'submit' | 'reset'; // Added 'type' property
}

/**
 * Props for a common input component.
 */
export interface InputProps {
  id: string;
  label: string;
  type?: string;
  value: string;
  onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => void;
  placeholder?: string;
  className?: string;
  rows?: number;
}

/**
 * Props for a common dropdown select component.
 */
export interface SelectProps {
  id: string;
  label: string;
  value: string;
  onChange: (event: React.ChangeEvent<HTMLSelectElement>) => void;
  options: { value: string; label: string }[];
  className?: string;
}

/**
 * Props for a common checkbox group component.
 */
export interface CheckboxGroupProps {
  label: string;
  options: { value: string; label: string }[];
  selectedValues: string[];
  onChange: (values: string[]) => void;
  className?: string;
}

/**
 * Props for a common slider component.
 */
export interface SliderProps {
  id: string;
  label: string;
  value: string;
  onChange: (value: string) => void;
  options: string[]; // Array of string values for the slider
  className?: string;
}

/**
 * Represents a hot business opportunity discovered by the AI.
 */
export interface HotOpportunity {
  id: string;
  category: string;
  description: string;
  monthlySearchVolume: string;
  competitorsAnalyzed: number;
  platformMentioned: string;
  growthPotential: string;
  easeOfEntry: 'Low' | 'Medium' | 'High';
  trendImpact: string[];
  keyPlayers: string[];
  score: number; // New field for overall score
}

/**
 * Props for the HotOpportunities component.
 */
export interface HotOpportunitiesProps {
  opportunities: HotOpportunity[];
  onViewDetails: (opportunity: HotOpportunity) => void;
  lastUpdateDate: string;
}

/**
 * Props for the OpportunityDetailModal component.
 */
export interface OpportunityDetailModalProps {
  isOpen: boolean;
  onClose: () => void;
  opportunity: HotOpportunity | null;
}